### ISSUE TITLE
Next chunk pointer wrong in +sarah's profile

### ISSUE THREAD

**Issue by larrysalibra** [blockstack/resolver#39]
From https://twitter.com/larrysalibra/status/584473307480633344

`next` is pointing to `"i/sarah-2"` when it should be pointing to `"i/sarah-1"`

Observed problem as of namecoin block 260422.

![screen shot 2015-04-05 at 5 39 22 am](https://cloud.githubusercontent.com/assets/597182/6994809/c40d0e9c-db58-11e4-9a1e-f9674d3e4217.png)

![screen shot 2015-04-05 at 5 39 49 am](https://cloud.githubusercontent.com/assets/597182/6994805/aec7c39c-db58-11e4-9db2-5491d2602a0b.png)

![screen shot 2015-04-05 at 5 40 07 am](https://cloud.githubusercontent.com/assets/597182/6994804/ab55b944-db58-11e4-8636-8bfeac307e89.png)

![screen shot 2015-04-05 at 5 40 52 am](https://cloud.githubusercontent.com/assets/597182/6994816/d9a956fc-db58-11e4-939c-fb144a171be0.png)

**Comment by muneeb-ali** [comment]
There are no next pointers anymore, since we moved away from Namecoin.
